import * as anchor from "@coral-xyz/anchor";
import { Program } from "@coral-xyz/anchor";
import { PublicKey, Connection, Keypair } from "@solana/web3.js";
import { createHash } from "crypto";
import * as fs from 'fs';
import * as os from 'os';

// Path to IDL generated by anchor build
const IDL_PATH = "../target/idl/orin_identity.json";

async function runSimulation() {
    console.log("🎮 ORIN Frontend Simulator Started...\n");

    const idl = JSON.parse(fs.readFileSync(IDL_PATH, "utf8"));
    const connection = new Connection("http://127.0.0.1:8899", "confirmed");

    // Load Local Solana Wallet (~/.config/solana/id.json)
    const secretKeyString = fs.readFileSync(os.homedir() + "/.config/solana/id.json", 'utf8');
    const secretKey = Uint8Array.from(JSON.parse(secretKeyString));
    const walletKeypair = Keypair.fromSecretKey(secretKey);

    const wallet = new anchor.Wallet(walletKeypair);
    const provider = new anchor.AnchorProvider(connection, wallet, {
        commitment: "confirmed"
    });
    anchor.setProvider(provider);

    // Hardcode Program ID from Phase 1
    const PROGRAM_ID = new PublicKey("FqtrHgdYTph1DSP9jDYD7xrKPrjSjCTtnw6fyKMmboYk");
    const program = new Program(idl as anchor.Idl, provider);

    // Create a unqiue email for this run
    const testEmail = `guest_${Math.floor(Date.now() / 1000)}@orin.network`;
    const emailHashBuffer = createHash("sha256").update(testEmail.toLowerCase().trim()).digest();
    
    // Derive PDA based on the integration spec
    const [guestPda] = PublicKey.findProgramAddressSync(
      [Buffer.from("guest"), emailHashBuffer],
      PROGRAM_ID
    );

    console.log(`👤 Using Wallet: ${wallet.publicKey.toBase58()}`);
    console.log(`🔑 Derived Guest PDA: ${guestPda.toBase58()}`);

    console.log(`\n[1/2] 📝 Sending InitializeGuest TX to Localnet...`);
    const tx1 = await program.methods
      .initializeGuest(Array.from(emailHashBuffer), "Demo Frontender")
      .accounts({
        guestProfile: guestPda,
        user: wallet.publicKey,
        systemProgram: anchor.web3.SystemProgram.programId,
      } as any)
      .rpc();
    console.log(`✅ Success! TX Hash: ${tx1}`);
    
    // Pause briefly to ensure sequential execution and distinct listener logs
    await new Promise(resolve => setTimeout(resolve, 2000));

    console.log(`\n[2/2] 🎛️ Sending UpdatePreferences TX to Localnet...`);
    const newPreferences = JSON.stringify({
      temp: 18.5,
      brightness: 100,
      light_color: "#A020F0", // Purple
      color_mode: "SLEEP"
    });

    const tx2 = await program.methods
      .updatePreferences(newPreferences)
      .accounts({
        guestProfile: guestPda,
        owner: wallet.publicKey,
      } as any)
      .rpc();
      
    console.log(`✅ Success! TX Hash: ${tx2}`);
    console.log("\n👀 Done! Switch over to your backend running `yarn start`.");
    console.log("You should see the account change events and MQTT triggers firing immediately!");
}

runSimulation().catch(console.error);
